name: java-spring-jobrunner-example
services:
  app:
    hostname: jobrunner-app
    build:
      context: .
      args:
        - APPLICATION_YML_FOLDER_PATH=${APPLICATION_YML_FOLDER_PATH}
    image: maiconfz/java-spring-jonrunner-example/app:${VERSION:-latest}
    profiles: [ "app" ]
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "9000:9000"
  db:
    hostname: jobrunner-db
    image: postgres:15-alpine
    profiles: [ "app", "db", "dev" ]
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6543:5432"
    volumes:
      - maiconfz-java-spring-jonrunner-example-jobrunner-db-pgdata:/var/lib/postgresql/data
volumes:
  maiconfz-java-spring-jonrunner-example-jobrunner-db-pgdata:
