/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.maiconfz.java_spring_jobrunner_example.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
